services:
    app:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - /app/dist
        environment:
            - NODE_ENV=development
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=1234
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        working_dir: /app

    db:
        image: mariadb:latest
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: 1234
            MARIADB_USER: root
            MARIADB_PASSWORD: 1234
            MARIADB_DATABASE: edgeTechDB
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost']
            interval: 5s
            timeout: 3s
            retries: 3
        command: --skip-grant-tables

    redis:
        image: redis:latest
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 3

volumes:
    db_data:
    redis_data:
